version: "3.7"

services:
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - ./.env
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/storeum_dev
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  postgres:
    image: "postgres:14-alpine"
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=storeum_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#    volumes:
#      - ./init-db/:/docker-entrypoint-initdb.d/
volumes:
  pg_data:
