version: "3.7"

services:
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - ./.env.dev
  postgres:
    image: "postgres:14-alpine"
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
#      - ./init-db/:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=storeum_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
volumes:
  pg_data:
