spring:
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PWD}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

#server:
#  port: 8888


# App Properties
storeum:
  app:
    jwtSecret: ${STOREUM_JWT_SECRET}
    jwtExpirationMs: ${STOREUM_JWT_EXPIRE_TIME}
    jwtRefreshExpirationMs: ${STOREUM_JWT_REFRESH_EXPIRE_TIME}
#debug: true
#logging:
#  level:
#    org:
#      springframework:
#        context: DEBUG