# DB props
spring:
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    url: jdbc:postgresql://postgres:5432/storeum_dev
    username: postgres
    password: postgres
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

# App Properties
storeum:
  app:
    jwtSecret: 1
    jwtExpirationMs: 1