spring:
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PWD}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        jdbc:
          lob:
            non_contextual_creation: true
  #    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: storeum.app@gmail.com
    password: ""
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# App Properties
storeum:
  app:
    jwt-secret: ${STOREUM_JWT_SECRET}
    jwt-expiration-ms: ${STOREUM_JWT_EXPIRE_TIME}
    jwt-refresh-expiration-ms: ${STOREUM_JWT_REFRESH_EXPIRE_TIME}
#debug: true
#logging:
#  level:
#    org:
#      springframework:
#        context: DEBUG