spring:
  sql:
    init:
      mode: always
  datasource:
    initialization-mode: always
    url: jdbc:postgresql://postgres:5432/storeum_mvp
    username: postgres
    password: 2281488
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

# App Properties
storeum:
  app:
    jwtSecret: 1
    jwtExpirationMs: 1